<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKxin2tp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKxin2tp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKxin2tp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKxin2tp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKxin2tp\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Kxin2tp',
    'container.build_id' => 'bfef21b5',
    'container.build_time' => 1544114023,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKxin2tp');
